// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvFe2-3Jk7pQH4EoN3BA_JdjBcagAqVuY',
    appId: '1:564931279897:android:be69576b6c54850796fe88',
    messagingSenderId: '564931279897',
    projectId: 'garnbarn',
    storageBucket: 'garnbarn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnuaujWGq8BOU-Y5apnqzlNiBU3QpWtTM',
    appId: '1:564931279897:ios:25ef67f5fb2d035b96fe88',
    messagingSenderId: '564931279897',
    projectId: 'garnbarn',
    storageBucket: 'garnbarn.appspot.com',
    iosClientId: '564931279897-v5qljhuqno04epqfrumjbunji59p9mks.apps.googleusercontent.com',
    iosBundleId: 'com.garnbarn.garnbarn-mobile',
  );
}
