name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Use Flutter"
        uses: subosito/flutter-action@v1.5.3
      - name: "Install Dependencies"
        run: flutter pub get
      - name: "Run Test"
        run: flutter test --coverage
      - name: Submit coverage data to Codecov
        run: bash <(curl -s https://codecov.io/bash)